### ISSUE TITLE
[Dev-log] 09월 30일 Minthug

### ISSUE THREAD

**Issue by Minthug** [codestates-seb/seb39_main_008#94]
### 오늘 진행된 작업  
Like class 구현 작업을 진행
Diary Post 에러 해결

### 오늘 진행된 작업 에서 겪은 어려움이나 에러에 대하여 적어주세요
Like 자체가 예약어와 겹쳐 에러를 발생해서
모든 Like -> Heart 로 예약어에 영향받지않게 수정 작업

Diary Post가 전혀 진행되지않았지만, Dto 및 Controller 수정을 통해 post는 가능하나
Jwt 인가 문제인지 member 정보를 받아오지못하고있어 Debug를 통해 문제 해결에 노력중

### 내일 진행 예정인 작업을 간단히 적어주세요
Diary가 무사히 해결됬을 경우, comment GET 부분을 프론트측과 통신해본 이후
문제점을 찾아볼 예정

**Comment by adeline0618** [comment]
🤗화이팅입니다.
